### ISSUE TITLE
doesn't work, at all

### ISSUE THREAD

**Issue by TheRealMiRRoRMaN** [mamei16/LLM_Web_search#11]
tried everything, errors everywhere.

why can't anybody write a good search thingie? i literally, LITERALLY tried them all this is the last i tried.

and yeah i followed every step of the way.

**Comment by lstep** [comment]
> tried everything, errors everywhere.
> 
> why can't anybody write a good search thingie? i literally, LITERALLY tried them all this is the last i tried.
> 
> and yeah i followed every step of the way.

Errors everywhere ?! It worked for me (except DDG has now a rate limiting). No error at all except that.
It would be nice to give a little more information to see what is wrong...

**Comment by mamei16** [comment]
It appears that you have some difficulties installing and using extensions, based on the other issues you have created (https://github.com/RandomInternetPreson/LucidWebSearch/issues/4#issue-2069166038 and https://github.com/simbake/web_search/issues/19). You seem frustrated, but venting your frustration in this way is not helpful, as @lstep already pointed out. This seems to be an issue with you, not the extension, so I'm going to close this.

**Comment by TheRealMiRRoRMaN** [comment]
Did everything according to the book, just tried every single step again, even saved a new instruction panel for it

Traceback (most recent call last):
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\gradio\blocks.py", line 1559, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\gradio\blocks.py", line 1447, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\gradio\components\dropdown.py", line 241, in postprocess
    self._warn_if_invalid_choice(y)
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\gradio\components\dropdown.py", line 229, in _warn_if_invalid_choice
    if self.allow_custom_value or y in [value for _, value in self.choices]:
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MiRR0RMaN\.conda\envs\textgen\Lib\site-packages\gradio\components\dropdown.py", line 229, in <listcomp>
    if self.allow_custom_value or y in [value for _, value in self.choices]:
                                                  ^^^^^^^^
ValueError: too many values to unpack (expected 2)
Output generated in 5.66 seconds (7.07 tokens/s, 40 tokens, context 399, seed 1067770052)

[mamei16[ DONT CLOSE IT JANNY I ONLY HAVE PROBLEMS WITH THESE SEARCHES YES, DONT OVERDO YOUR JOB RELAX

**Comment by TheRealMiRRoRMaN** [comment]
This seems to be an issue with you, not the extension, so I'm going to close this.

not even remotely true, i even wrote extensions myself.

**Comment by mamei16** [comment]
For future reference, this is a known issue with the web UI, see https://github.com/oobabooga/text-generation-webui/issues/5118 and https://github.com/oobabooga/text-generation-webui/issues/4313.
