### ISSUE TITLE
How do I get the LLM to type Search_web("") in its response? I'm using dolphin 2.9.3

### ISSUE THREAD

**Issue by Sambouza** [mamei16/LLM_Web_search#117]
So I have set everything up, requirements.txt and all, and when I trick the AI to say "search_web("")" it **does work**, but how do I get it to do that on its own when it sees suitable?

Like if I say "search about LLMs" it says it cant search the web
and when I put the instructions on how to using Search_web("") in its context, it does not work and it just says "Sure let me fetch that for you" then never actually using the function.

Thanks in advance and please write a more comprehensive installation guide for us newbies :)

**Comment by mamei16** [comment]
Hey m8, some fine-tuned models like dolphin 2.9.3 can have trouble with outputting the search command. The easiest way to solve the issue is to use the original model (unless that model is an old model like Llama 2).  

Otherwise, you'll have to do some "prompt engineering" to come up with a system prompt that consistently makes the model output the search command. Which phrasing works best varies from fine tune to fine tune, so you'll have to experiment. Sometimes, using ChatGPT or Copilot for inspiration can help. 

Can you point to some parts in the README that you found unclear? I'm trying to keep a balance between being somewhat beginner friendly, while also not becoming overly verbose.

**Comment by Sambouza** [comment]
> Hey m8, some fine-tuned models like dolphin 2.9.3 can have trouble with outputting the search command. The easiest way to solve the issue is to use the original model (unless that model is an old model like Llama 2).
> 
> Otherwise, you'll have to do some "prompt engineering" to come up with a system prompt that consistently makes the model output the search command. Which phrasing works best varies from fine tune to fine tune, so you'll have to experiment. Sometimes, using ChatGPT or Copilot for inspiration can help.
> 
> Can you point to some parts in the README that you found unclear? I'm trying to keep a balance between being somewhat beginner friendly, while also not becoming overly verbose.

Bummer. I find mistral and its fine-tunes to perform much better and responding faster than Llama. I'll try Llama once it finishes downloading. But when actually tricking it to say search_web("") it actually gave me a sensible response about what it just searched. I still do not know how to make it do that on its own. Does it write search_web on its own or do I need a specific .yaml context file or should I write a custom line in the context? Still unsure.

Anyway, here are some areas where I got stuck
1. During installation it was mostly due to me being dumb but I updated the extension by using the cmd_windows.bat and running the pip requirements.txt thingy instead of following the installation guide since other extensions do this, so great job on showcasing the proper way to do this by using the update wizard
2. It's weird how it's mentioned `Run the appropriate update_wizard` in step 2 in installation but uses `python server.py --extension LLM_Web_search` in step 3. I'm sure people downloading this extension as their first oobabooga extension would find it puzzling. Writing alongside that `Or run the appropriate start script and enable it under the session tab` is going to be very helpful
3. In usage, I had no idea what a hyperparameter generator is and even after searching it I still had no clue how to use that in oobabooga, so maybe writing a separate wiki page or linking to an existing one on oobabooga terminology would be lovely! I would rather spend time reading terminology before reading the actual installation guide.

Anyhow enough blabbering from me, thanks for sharing this extension dude

**Comment by mamei16** [comment]
The original Mistral-Nemo-Instruct model works very well with the extension, so you could try that one too (but only if you have >= 12GB VRAM).   
To get a model to search on its own, you need to convince it do so via a custom system message/prompt, where you explain exactly in which cases the model should output the search command. When you have it working, the model will write `Search_web("thing to search")` completely on it's own, when it deems that it's appropriate to do so.

To try one the example system prompts that come with the extension, simply select it in the dropdown. 
![Screenshot_20241023_174032](https://github.com/user-attachments/assets/2c565605-cd2f-4de8-9473-58295ada10d4)
This will automatically overwrite the custom system message and make the model aware of the `Search_web` command.

I appreciate the blabbering, I'll go ahead and make those details clearer in the README :+1:

**Comment by mamei16** [comment]
Hi again,   
I just tried Mistral Nemo 12B after not using it for a while and noticed that now none of the example system prompts could convince it to use the search command.  
However, after I created a new generation parameter preset, the model consistently used the search command!
[preset.zip](https://github.com/user-attachments/files/17532245/preset.zip)
To try it out, you have to unzip it and place the file into your `text-generation-webui/presets/` folder. Then you can select the preset under the Parameters tab. Hope it works for you too!
