### ISSUE TITLE
Web searches fail when using DeepSpeed

### ISSUE THREAD

**Issue by TheCyberQuake** [mamei16/LLM_Web_search#18]
**Describe the bug**
Using Linux, running the extension without deepspeed runs perfectly fine.
Running with deepspeed causes to search to throw this error:
'weight' must be 2-D
**To Reproduce**
1. Install deepspeed
2. launch oobabooga using deepspeed
3. Use a prompt that initiates a query response from the bot
4. LLM_web_search gives "'weight' must be 2-D"

**Expected behavior**
Search to go through when using deepspeed

**Screenshots**

**Additional context**

**Comment by mamei16** [comment]
Can you confirm that this error only occurs when the extension is loaded? If yes, please paste the entire error output in another comment.

**Comment by TheCyberQuake** [comment]
Did more testing, something on my end was wack but the next day it was fine, even though I didn't change anything.
