### ISSUE TITLE
Filter request from bot response

### ISSUE THREAD

**Issue by TheCyberQuake** [mamei16/LLM_Web_search#19]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just think it would be cool to prevent the search command given as a response from the AI to not show up in the final chat

**Describe the solution you'd like**
To make the responses seem cleaner/smarter, perhaps we could filter out the search command the bot gives. Essentially if this extension is triggered by regex to start a search/open url, remove it from their response. Not sure if that's possible, but would allow responses to feel much more natural without the command to search showing up.

**Describe alternatives you've considered**

**Additional context**

**Comment by mamei16** [comment]
I think that it's important to always show evidence of each web search the model has triggered. Current models are still likely to falsely claim to have used the search command, even though they have not. See the following example:

![Screenshot_20240313_161810](https://github.com/mamei16/LLM_Web_search/assets/25900898/8082956f-c200-4639-a53e-792350e07841)

However, I agree that the current way of keeping the raw search command in the output is not very clean.

**Comment by TheCyberQuake** [comment]
I fully agree that there needs to be something to indicate it actually ran a search, as like your image I've had it tell me it searched when it clearly didn't (and was a huge part in the process of tweaking the character context to get it to search nearly every time)
But some other way outside of showing it directly in the response would in my opinion be ideal, though how to go about that I'm not entirely sure of.
Primarily, the reason I bring this up is for people who like to use text to speech. Current implementation causes the TTS to read out the command.

**Comment by mamei16** [comment]
Hi, I have thought about your idea and still don't think filtering the command completely is a good idea.   
However, you mention TTS. I imagine it maybe reads the underscore and parentheses in the command out loud, which could be annoying. What do you think about having an option to replace the search command with a more TTS friendly string, like "Searching for"? Then, in the final output, it would automatically replace "Search_web("GPT-4")" with "Searching for GPT-4".

**Comment by ill13** [comment]
I think this can be approached via another extension that simply modifies the ouput.

I believe that just creating an extension that uses the..
 >`def output_modifier(string, state, is_chat=False):` 

...function with `string.replace()` or regex magic can achieve the results you are looking for -without any changes to *LLM_Web_search*.
