### ISSUE TITLE
updating conda environment "access denied"

### ISSUE THREAD

**Issue by Magnus19243** [mamei16/LLM_Web_search#32]
New to this stuff, pretty sure its something simple but couldnt figure out how to do step 3 as i just get access denied even with administritive privelege, i have entered through cmd_windows.bat so it should access the virtual environment.

this step is most likely neccesary as just installing the requirment.txt isnt making it work.

local ai working fine otherwise btw.

**Comment by mamei16** [comment]
That sounds strange. Perhaps try running `update_wizard_windows.bat` instead and choose `Install/update extensions requirements`  when the program asks "What would you like to do?"

**Comment by Magnus19243** [comment]
yup did that, it installed everything and extension appears on the tabs, i set it to gpt4 prompt, and used the command Search_web("the thing i want it to search") in chat-instruct mode, but it doesnt use the web and just gives me old info like always.

hence why i thought that step 3 was crucial and diffrent from installing requirments.

**Comment by Magnus19243** [comment]
also tanked my tps to the ground lol, went from 29 to 3.

**Comment by mamei16** [comment]
Ah I see, in this case the problem is that *you* are trying the use the command, but it's only the model that can do that. So instead of writing Search_web("the thing i want it to search") yourself, try asking the model about the thing you want to search. A model that's good at following instructions and function calling should then itself decide to write Search_web("the thing i want it to search") to trigger a web search. There's always some randomness involved, so if the gpt4 prompt doesn't work with the model, try `second_person_command_last` or one of others.

**Comment by Magnus19243** [comment]
oh nice, worked once with the default system prompt, tried 10 times for diffrent things but didnt search, other models no hit.

my ai model seems decently smart despite being 7b, its this "https://huggingface.co/cognitivecomputations/dolphin-2.8-mistral-7b-v02"

guese 7b just cant cut it then.

**Comment by mamei16** [comment]
Yeah, 7B is definitely the minimum, although that's what I use as well as a GPU poor person. But it does vary from 7B to 7B. I had to try hard to convince the new WizardLM-2-7B to search, while Hermes-2-Pro-Mistral-7B is pretty consistent.

**Comment by mamei16** [comment]
Alright, I have now added an option so you can force the model to search the web using a checkbox under the "Generate" button.

**Comment by Magnus19243** [comment]
awesome thanks that would be usefull but now the ai just says Search_web "whatever i told it to search", no  search done.

**Comment by mamei16** [comment]
are you really using dolphin-2.8-mistral-7b-v02? I worry that it might be a little intellectually challenged. Put this in the `Search command regex string` field, save settings and pray to RNGesus that the model is able to do what it's supposed to:
```regex
[Ss]earch_web:?[\( ]?(?:["'])(.*)(?:["'])\)?
```

**Comment by Magnus19243** [comment]
NICE! thanks man much appreciated! dont even need to press the force web search now :)
