### ISSUE TITLE
doesn't start

### ISSUE THREAD

**Issue by thejohnd0e** [mamei16/LLM_Web_search#36]
![Screenshot - 2024-05-06 10 11 56](https://github.com/mamei16/LLM_Web_search/assets/115493464/be3c8f01-0173-4cc9-b618-0a3f1c5d4d99)

**Comment by lstep** [comment]
You need to do a `pip install -r requirements.txt` to install the required modules. Here, you're missing the `duckduckgo-search` python  module.

**Comment by thejohnd0e** [comment]
> You need to do a `pip install -r requirements.txt` to install the required modules. Here, you're missing the `duckduckgo-search` python module.

![Screenshot - 2024-05-06 10 55 00](https://github.com/mamei16/LLM_Web_search/assets/115493464/d4101a4a-28c8-4059-8fe6-f3d4e881ef89)

![Screenshot - 2024-05-06 10 54 25](https://github.com/mamei16/LLM_Web_search/assets/115493464/8986eb4f-8f53-4c76-8c57-fc265b40980d)

![Screenshot - 2024-05-06 10 55 53](https://github.com/mamei16/LLM_Web_search/assets/115493464/eb50ede2-3887-4d9d-bd4f-3c2891a4ede5)

**Comment by lstep** [comment]
Is your oobabooga instance using any kind of virtual env (like venv, or conda) ? If that is the case, you need to be in that environment when doing the `pip intall`.

**Comment by thejohnd0e** [comment]
> Is your oobabooga instance using any kind of virtual env (like venv, or conda) ? If that is the case, you need to be in that environment when doing the `pip intall`.

Of course I install dependencies from the folder where the extension is located, but I still don't understand why it's not working.

![Screenshot - 2024-05-06 16 58 50](https://github.com/mamei16/LLM_Web_search/assets/115493464/c4d1672a-97b4-44c8-b5df-563eda75f832)
