### ISSUE TITLE
The search tool encountered an error and did not return any results.

### ISSUE THREAD

**Issue by phr00t** [mamei16/LLM_Web_search#4]
![image](https://github.com/mamei16/LLM_Web_search/assets/5983470/b9dee9e8-4619-41bf-9d41-20832704118e)

Settings:

![image](https://github.com/mamei16/LLM_Web_search/assets/5983470/f1842538-cb71-4339-81e5-d94245c426bb)

**Comment by mamei16** [comment]
Hi again! If you want to use a custom regex, please verify that it fulfills that capture group requirement [described in the readme](https://github.com/mamei16/LLM_Web_search/blob/main/README.md#using-a-custom-regular-expression). If you test your regex using https://www.debuggex.com/, you can see that the search query will be matched by the third capture group, when it should be matched by the first. To use "non-capturing" groups, add the prefix `?:` at the start of each group. Please try with the following modified version of your regex:
```
(?:S|s)earch_(?:W|w)eb: "(.*)"
```

**Comment by phr00t** [comment]
Ahhhh, that worked!

However, I noticed it didn't save my custom regex when I opened it up again. How can I save this to keep for later? Saving the "session UI" didn't seem to grab stuff from the LLM web search tab.

**Comment by mamei16** [comment]
Nice!

Saving the settings wasn't an option before, so I added it now: ec952eb4bcc30e52a0d3cc9ffb9894a0cbd83d81.

**Comment by phr00t** [comment]
This is all fixed, thank you!
