### ISSUE TITLE
Open_url results didn't seem to get used in the response?

### ISSUE THREAD

**Issue by phr00t** [mamei16/LLM_Web_search#6]
![image](https://github.com/mamei16/LLM_Web_search/assets/5983470/895c7ecd-5efb-42e4-baa1-d739c7661fd4)

![image](https://github.com/mamei16/LLM_Web_search/assets/5983470/37f2d64b-b47f-4813-b3fc-ea4847e58620)

![image](https://github.com/mamei16/LLM_Web_search/assets/5983470/d95053f4-012c-41a1-a153-aec24616988b)

**Comment by phr00t** [comment]
What is very strange though is the context number: see how it actually went down after reading? Very odd.

**Comment by mamei16** [comment]
True, that is very weird indeed. Don't think I have seen that before.

**Comment by mamei16** [comment]
I have been able to reproduce this behavior by setting the context length to a low value (1024). But this is not an issue with the extension, but likely expected behavior stemming from how llama.cpp handles the input exceeding the max. context length. Try increasing the context length.

**Comment by phr00t** [comment]
Hmmm... I usually put in at least 4096, but maybe this response even broke that limit. Thank you for the help!
