### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by Dartvauder** [mamei16/LLM_Web_search#7]
![image](https://github.com/mamei16/LLM_Web_search/assets/140557322/d45130a9-ee13-44ce-806d-aff33e74817d)

Hello. I have a problem. At first there were two errors due to the fact that there were not enough unstructured and langchain modules. I installed them via windows_cmd.bat. As a result, the WebUI does not start. What is the problem and how to solve it?

P.S. Windows 11

**Comment by mamei16** [comment]
Hi, are you running the language models on your GPU or CPU?

**Comment by Dartvauder** [comment]
Please excuse me for the long wait for an answer. Was offline. I run language models only via cpu. But I have a gpu. I just use it for automatic1111

**Comment by mamei16** [comment]
No problem! By default, the extension will try to load the embedding model into VRAM to use the GPU, so this could cause the endless loading in your case. Please try copying the following file into the LLM_Web_search folder: [settings.json](https://github.com/mamei16/LLM_Web_search/files/13788415/settings.json). In it, I have set the option `cpu only` to `true`.

**Comment by Dartvauder** [comment]
> No problem! By default, the extension will try to load the embedding model into VRAM to use the GPU, so this could cause the endless loading in your case. Please try copying the following file into the LLM_Web_search folder: [settings.json](https://github.com/mamei16/LLM_Web_search/files/13788415/settings.json). In it, I have set the option `cpu only` to `true`.
> 

Thanks a lot! Everything works as it should. Good luck with further development of extension!
